#pragma once

enum GoalDataProc {
	None = 0x0,
	CurrentPosition = 0x1,
	FindWayPoint = 0x2,
	FindClosestWayPoint = 0x3,
	FindAssignedWayPoint = 0x4,
	FindTarget = 0x5,
	GoalDataProc_GenerateShortBurst = 0x6,
	GoalDataProc_GenerateMediumBurst = 0x7,
	GoalDataProc_GenerateLongBurst = 0x8,
	GoalDataProc_GenerateForwardThrowingPosition = 0x9,
	GoalDataProc_GenerateBackwardThrowingPosition = 0xA,
	FindTargetAtLastKnownPosition = 0xB,
	FindPlayerTarget = 0xC,
	FindInvestigateCoverPoint = 0xD,
	FindOffensiveCoverPoint = 0xE,
	FindInterruptedCoverPoint = 0xF,
	FindLastKnownThreatCoverPoint = 0x10,
	FindFleePoint = 0x11,
	FindOriginPoint = 0x12,
	FindWeaponPickup = 0x13,
	FindSearchPoint = 0x14,
	FindLastThreatSeenPos = 0x15,
	FindDisturbance = 0x16,
	FindOutOfCoverGrenateThrowingPosition = 0x17,
	FindPositionSideways = 0x18,
	FindUnconsciousFriend = 0x19,
	FindOccupation = 0x1A,
	FindOccupationAssigned = 0x1B,
	FindSniperSpot = 0x1C,
	FindFirePoint = 0x1D,
	FindFarFirePoint = 0x1E,
	FindNearestCop = 0x1F,
	FindAlarmTrigger = 0x20,
	FindWanderPos = 0x21,
	FindSearchPointVisible = 0x22,
	FindCoverlessAttackPosition = 0x23,
	FindCoverlessLastKnownLocationPosition = 0x24,
	FindCoverlessInvestigatePosition = 0x25,
	FindClosestAlarmPanel = 0x26,
	FindClosestSniperFirePointNoNeedForVisibility = 0x27,
	FindLastOrangeZonePosition = 0x29,
};

class GoapPlanner {

};
